title: viky.ai
baseurl: ""
url: "https://www.viky.ai"
logo: /site_assets/img/viky-ai-logo.png

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

permalink: /blog/:year/:month/:day/:title

feed:
  path: blog/atom.xml

markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

sass:
  sass_dir: site_assets/css

exclude:
  - README.md
  - CONTRIBUTING.md
  - Dockerfile

host: 0.0.0.0
