title: ""
baseurl: ""
url: "https://www.viky.ai"
logo: /site_assets/img/viky-ai-logo.png

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

features:
  user_registration_disabled: false

excerpt_separator: <!--keep reading-->

permalink: pretty

feed:
  path: blog/atom.xml

defaults:
  -
    scope:
      path:            "404.html"
    values:
      sitemap:         false
  -
    scope:
      path:            "50x.html"
    values:
      sitemap:         false
  -
    scope:
      path:            "about/privacy-policy/index.md"
    values:
      sitemap:         false
  -
    scope:
      path:            "about/terms-of-use/index.md"
    values:
      sitemap:         false
  -
    scope:
      path:            "about/terms-and-conditions-of-sale/index.md"
    values:
      sitemap:         false
  -
    scope:
      path:            "doc/guides/markdown-reference/index.md"
    values:
      sitemap:         false

markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

sass:
  sass_dir: site_assets/css

exclude:
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENCE.txt
  - Dockerfile
  - deployment
  - conf

host: 0.0.0.0
