title: www.viky.ai
baseurl: ""
url: "https://www.viky.ai"
logo: /site_assets/img/viky-ai-logo.png

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

permalink: /blog/:year/:month/:day/:title

markdown: kramdown
sass:
  sass_dir: site_assets/css

exclude:
  - README.md
  - CONTRIBUTING.md

host: 0.0.0.0
