name: Build and Publish viky-ai website to Dockerhub
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 1 * * 0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Docker Repository vikyai/doc
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: vikyai/doc
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: "true"
          # Cache docker build
          cache: ${{ github.event_name != 'schedule' }}
