name: Build and Publish viky-ai website to Dockerhub
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Docker Repository vikyai/doc
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: vikyai/doc
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
